node {
  name = "emqx@127.0.0.1"
  cookie = "emqxsecretcookie"
  data_dir = "/opt/emqx/data"
}

log {
  level = warning
  file {
    enable = true
    path = "/opt/emqx/log/emqx.log"
  }
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 1024000
}

listeners.ws.default {
  bind = "0.0.0.0:8083"
  websocket.mqtt_path = "/mqtt"
}

dashboard {
  listeners.http {
    bind = 18083
  }
  default_username = "admin"
  default_password = "public"
}

authorization {
  no_match = allow
  deny_action = ignore
}
