services:
  - type: web
    name: iot-emqx-broker
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./docker/emqx/Dockerfile.render
    dockerContext: .
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: TZ
        value: America/Bogota
      - key: EMQX_NODE__NAME
        value: emqx@127.0.0.1
      - key: EMQX_NODE__COOKIE
        generateValue: true